apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test
spec:
  containers:
  - name: tcp-echo
    image: busybox
    command:
    - nc
    - -k
    - -l
    - -p
    - '2000'
    - -e
    - sh
    - -c
    - | 
      echo "Received new TCP connection" >&2
      while read msg
      do
        echo "Received: $msg" >&2
        echo "You said: $msg"
      done
      echo "Connection closed" >&2
      echo >&2
    ports:
    - name: tcp2000
      containerPort: 2000
      protocol: TCP
  - name: udp-echo
    image: busybox
    command:
    - nc
    - -u
    - -k
    - -l
    - -p
    - '3000'
    ports:
    - name: udp3000
      containerPort: 3000
      protocol: UDP
  - name: grpc-echo
    image: quay.io/mhausenblas/yages:0.1.0
    command:
    ports:
    - name: grpc9000
      containerPort: 9000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  selector:
    app: test
  ports:
  - name: tcp2000
    port: 2000
    protocol: TCP
  - name: udp3000
    port: 3000
    protocol: UDP
  - name: grpc9000
    port: 9000
    protocol: TCP
